weights: /opt/data/private/CODE/AAAI-CODE/yolov5_CoLD/weights/yolov5x6.pt
cfg: models/hub/yolov5x6.yaml
data: data/OGSOD.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 400
batch_size: 32
imgsz: 256
rect: false
resume: ''
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: cold
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 50
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/cold
